### ISSUE TITLE
User & Role - User version should be integer

### ISSUE THREAD

**Issue by caohhung** [scattm/DanceCat#83]
User.version should be integer and can't be string value.
Please investigate this bug

**Comment by scattm** [comment]
I checked SQLite schema after create, the table creation was right, so I don't think the problem is in our code. You can take a look at this:
```
CREATE TABLE user (
       	id INTEGER NOT NULL,
       	email VARCHAR(255) NOT NULL,
       	password VARCHAR(255) NOT NULL,
       	"isActive" BOOLEAN NOT NULL,
       	"createdOn" DATETIME,
       	"lastLogin" DATETIME,
       	"lastUpdated" DATETIME,
       	version INTEGER NOT NULL,
       	PRIMARY KEY (id),
       	CHECK ("isActive" IN (0, 1))
);
``` 

Then I research about data types in [SQLite](https://www.sqlite.org/datatype3.html), here is what they said:

> Any column in an SQLite version 3 database, except an INTEGER PRIMARY KEY column, may be used to store a value of any storage class.

Pretty funny, but I guess we can just ignore this case, or test it using other RDBMS.

**Comment by caohhung** [comment]
God bless us
